# Generated by Django 4.2.7 on 2023-11-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDelPaciente', models.CharField(max_length=100, verbose_name='Nombre del Paciente')),
                ('dpi', models.CharField(max_length=20, verbose_name='DPI')),
                ('fechaDeNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('dirección', models.TextField(verbose_name='Dirección')),
                ('recetaMedica', models.TextField(blank=True, null=True, verbose_name='Receta Médica')),
                ('numeroTelefonico', models.CharField(max_length=15, verbose_name='Número Telefónico')),
                ('fotoDelPaciente', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto del Paciente')),
            ],
        ),
    ]
