# Generated by Django 4.2.7 on 2023-11-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Doctor')),
                ('numeroColegiado', models.CharField(max_length=20, verbose_name='Número de Colegiado')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('numeroTelefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Teléfono')),
                ('fotoDelDoctor', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Foto del Doctor')),
            ],
        ),
    ]
