# Generated by Django 4.2.7 on 2023-11-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0003_historialclinico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialClinico',
        ),
    ]
