# Generated by Django 4.2.7 on 2023-11-05 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0004_delete_historialclinico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libreria.doctor', verbose_name='Doctor')),
                ('nombreDelPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libreria.paciente', verbose_name='Paciente')),
            ],
        ),
    ]
