# Generated by Django 4.2.7 on 2023-11-06 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0006_rename_nombredelpaciente_historial_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Libreria.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Libreria.paciente', verbose_name='Paciente'),
        ),
    ]
